### ISSUE TITLE
Codahale Metrics Memory leak causing undeployment issues 

### ISSUE THREAD

**Issue by chris-mcc** [petergeneric/stdlib#10]
An issue has been raised over at https://github.com/dropwizard/metrics/issues/742 that by proxy affects the Stdlib.

It doesn't always cause a problem, but I have seen it preventing Tomcat undeploying an application and on a rare occasion (once) it caused an "this application has already been stopped" error inside some Resteasy code.

I have tried disabling the Metrics role and have only been getting the warnings so far.

**Comment by chris-mcc** [comment]
There's now a fix in the master branch of the Metrics library for Java 7+.  But it may take awhile for the 3.10.x to be fixed as they have to find a compatible way to do it in Java6.

**Comment by petergeneric** [comment]
Thanks chris, I finally got around to fixing this in 0ea57996ef27a137c7bfa0dc0546d84ba973ec45 !
