### ISSUE TITLE
Resteasy Client Factory Impl should support Proxy

### ISSUE THREAD

**Issue by chris-mcc** [petergeneric/stdlib#15]
Currently the ResteasyClientFactoryImpl does not support Proxies.

A good enhancement would be to pull this configuration in from the System properties or automatically use the System proxy info to support not only Proxy host, but Proxy auth as well.

The applicable system Properties would be:
http.proxyHost
http.proxyPort
http.proxyUser
http.proxyPassword

**Comment by petergeneric** [comment]
Because apache httpcomponents-client is being used to make the HTTP requests we should actually be able to delegate the proxy route planning to the JRE with ```SystemDefaultRoutePlanner``` - docs at https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e485

**Comment by chris-mcc** [comment]
I think that's the most ideal route.  I've heard it has problems/limitations in certain set-ups, but never came across it.

**Comment by petergeneric** [comment]
I've changed the code to use the JRE route planner. If you need to customise this further (or to work around an issue caused by the JRE's route planner) then you can use ```ResteasyClientFactoryImpl``` to create ```ResteasyClient``` instances for you, passing a ```Consumer<HttpClientBuilder> customiser``` to ```getOrCreateClient``` and have your consumer modify the HttpClientBuilder with your own route planner.
