### ISSUE TITLE
Dealing with wrong Content type from Rest services 

### ISSUE THREAD

**Issue by chris-mcc** [petergeneric/stdlib#16]
Whenever an external rest service uses an incorrect content type like text or the proxy blocks with a custom html page the error message is not the most accurate and in some cases has to be worked around.

When a service uses the incorrect content type we can create a custom MessageBodyReader to convert manually using the JaxbSerialiser or Jackson classes or in the case of an html page output the message to aid in debugging.

Another option could be to change the content type manually, but I think implementing a MessageBodyReader would be more flexible.

**Comment by petergeneric** [comment]
Could you clarify what you mean here? (and could you show the sort of inaccurate error you're referring to?) I'm very wary of re-interpreting the server's response when the Content Type header is wrong

**Comment by chris-mcc** [comment]
You can see what I mean here for the wrong content type:
http://sampleserver5.arcgisonline.com/arcgis/rest/services/Utilities/Geometry/GeometryServer/project?inSR=4326&outSR=27700&geometries=0,51&transformation=5339&transformForward=false&f=json

They actually use a non std content type of just text here.

You'll get a messagereader not found for text for type ....

The error page came from Microsoft StoreFront and consisted of a full html page.

Since you're wary re-interpreting the server's response, maybe just outputting the text and declaring type etc might be good for debugging purposes.

**Comment by petergeneric** [comment]
I'd argue they respond with a very standard Content Type, it's just wrong :)

What error do you see when the StoreFront server returns an HTML page? If the exception is being thrown by the library (rather than by resteasy) the ```RestException``` subclass (``UnboundRestException```) should include the JAX-RS ```ClientResponseContext```, accessible with ```getResponseContext``, which you should be able to use to retrieve the entity (which if the server responds with text/html should be a String)

**Comment by chris-mcc** [comment]
yeah, interesting workaround though.  The error message for Storefront would be cannot find messagebodyReader for text/html.  it's been awhile since I had to deal with that specific issue, I'm not sure what exact error message gets emitted.
