### ISSUE TITLE
Artifact Version Review

### ISSUE THREAD

**Issue by chris-mcc** [petergeneric/stdlib#19]
Hi,

Did a sweep to see if any newer versions exist.  They include:

Freemarker 2.3.23 - template improvements and bug fixes
guice/common
mockito-core in common has version set to 1.9.5 - 1.10.19 now exists

stdlib/
commons-lang - 2.6 is now out
commons-logging - 1.2 - Might be best to add a property for the version of this artifact, this is used in guice/ too
bcprov-jdk15on - 1.53 is now out 
xstream - 1.4.8 is now out
moxy - 2.6.1 is now out

I believe most should be fine to change, but some light regression testing would be good.

**Comment by petergeneric** [comment]
Thanks, I'll look into upgrading things... planning on dropping the xstream dependency btw - there's only one small helper class

**Comment by petergeneric** [comment]
Partially fixed.

The bugfixes in MOXy for 2.6.1 ( see https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=RESOLVED&bug_status=CLOSED&classification=RT&component=MOXy&list_id=12900122&order=component%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&product=EclipseLink&query_based_on=&query_format=advanced&resolution=FIXED&target_milestone=2.6.1 ) do not impact us, however the upgrade has passed testing.
I've also updated commons-lang and removed the xstream dependency.

I've left bcprov and commons-logging at their current versions for now

**Comment by petergeneric** [comment]
These deps have all been upgraded to or beyond the versions suggested in this ticket
