### ISSUE TITLE
TypeConverterService

### ISSUE THREAD

**Issue by ghost** [petergeneric/stdlib#24]
Greetings,

In commit https://github.com/chris-windwalker/stdlib/commit/b02361f66e642f7b028a9f82c89d054563da7a44

I have added a more generic version of a type class that you have.

Haven't quite finished it yet.  But It would would be a cleaner way to do it.  Btw it taps into the default converters for Enums etc.

**Comment by petergeneric** [comment]
Referenced commit is gone
