### ISSUE TITLE
A Possible NPE at line 280 of com.peterphi.std.guice.web.rest.auth.userprovider.HttpCallJWTUser

### ISSUE THREAD

**Issue by zhaoyangyingmu** [petergeneric/stdlib#48]
Hello,
I find that an NPE could possibly be triggered at line 280 of `com.peterphi.std.guice.web.rest.auth.userprovider.HttpCallJWTUser` because the return value of `get()` could return `null`.
```java
@Override
public String getName()
{
	final Map<String, Object> data = get();

	if (data.containsKey("name"))// data could be null and trigger an NPE.
		return String.valueOf(data.get("name"));
	else
		return getUsername();
}
@SuppressWarnings("unchecked")
private Map<String, Object> get()
{
	// other codes
	if (token != null)
	{
		try
		{
			if (requireSecure && !request.isSecure())
			{
				log.fatal(message);
				return null;// return unchecked null here.
			}
}
```
Maybe a null check is needed before dereferencing the variable `data`. Hopefully this suggestion is helpful!

**Comment by petergeneric** [comment]
Thanks for the report, I've fixed this issue by throwing an exception earlier in the process rather than returning null and causing a NPE
